"""JLCPCB manufacturability: check a board against JLCPCB's *authoritative* capabilities.

The capability values below are transcribed and cross-referenced from JLCPCB's own published
pages (NOT invented) -- see ``SOURCES``/``VERIFIED``. Re-verify when JLCPCB updates. The check
compares (1) the board's ACTUAL geometry and (2) its CONFIGURED design rules against these
limits, so the review is JLCPCB-meaningful rather than KiCad-default. Read-only.
"""

from __future__ import annotations

import json
from pathlib import Path

import sexpdata

from kicad_mcp.review.parse import _get, _getall, _getval, parse_board

# --------------------------------------------------------------------------- #
# authoritative capability data (cited, not hallucinated)
# --------------------------------------------------------------------------- #
SOURCES = (
    "https://jlcpcb.com/capabilities/pcb-capabilities",
    "https://www.schemalyzer.com/en/blog/manufacturing/jlcpcb/jlcpcb-design-rules",
)
VERIFIED = "2026-06-17"  # re-confirm against SOURCES after this date

# all values in mm. JLCPCB's minimums tighten on 4+ layer boards.
_LIMITS_1_2_LAYER = {
    "min_track_width": 0.127,  # 5 mil (1 oz outer)
    "min_clearance": 0.127,
    "min_via_drill": 0.30,
    "min_via_diameter": 0.60,
    "min_annular_ring": 0.15,
    "min_pth": 0.15,
    "min_copper_edge_clearance": 0.30,
}
_LIMITS_4PLUS_LAYER = {
    "min_track_width": 0.09,  # 3.5 mil
    "min_clearance": 0.09,
    "min_via_drill": 0.20,
    "min_via_diameter": 0.45,
    "min_annular_ring": 0.15,
    "min_pth": 0.15,
    "min_copper_edge_clearance": 0.30,
}
SUPPORTED_COPPER_OZ = (0.5, 1.0, 2.0)
SUPPORTED_THICKNESS_MM = (0.4, 0.6, 0.8, 1.0, 1.2, 1.6, 2.0)


def capabilities_for(copper_layers: int | None, copper_oz: float | None) -> dict:
    """JLCPCB min-feature limits (mm) for a board of this layer count + copper weight."""
    limits = dict(_LIMITS_4PLUS_LAYER if (copper_layers or 2) >= 4 else _LIMITS_1_2_LAYER)
    if (copper_oz or 1) >= 2:  # 2 oz copper needs wider min track/clearance
        limits["min_track_width"] = max(limits["min_track_width"], 0.20)
        limits["min_clearance"] = max(limits["min_clearance"], 0.20)
    return limits


# --------------------------------------------------------------------------- #
# standard stackups (one source: gsuberland, generated from JLCPCB's impedance API)
# --------------------------------------------------------------------------- #
STACKUP_SOURCE = (
    "https://github.com/gsuberland/jlcpcb_autogenerated_stackups (release-2025-05-09, "
    "generated directly from JLCPCB's impedance-template API)"
)
# JLCPCB's default stackup (outer 1 oz / inner 0.5 oz), keyed by (copper_layers, thickness_mm).
# A DATED snapshot of values JLCPCB revises; JLCPCB assigns the FINAL build stack at order time,
# so treat this as "JLCPCB's published standard", not "what JLCPCB will build for you".
STACKUPS = {
    (4, 1.6): {
        "code": "JLC04161H-7628",
        "layers": [
            {"type": "copper", "role": "outer copper (1 oz)", "thickness": 0.035},
            {"type": "prepreg", "role": "prepreg 7628", "thickness": 0.2104, "epsilon_r": 4.4},
            {"type": "copper", "role": "inner copper (0.5 oz)", "thickness": 0.0152},
            {"type": "core", "role": "core", "thickness": 1.065, "epsilon_r": 4.43},
            {"type": "copper", "role": "inner copper (0.5 oz)", "thickness": 0.0152},
            {"type": "prepreg", "role": "prepreg 7628", "thickness": 0.2104, "epsilon_r": 4.4},
            {"type": "copper", "role": "outer copper (1 oz)", "thickness": 0.035},
        ],
    },
}


def reference_stackup(copper_layers: int | None, thickness_mm: float | None) -> dict | None:
    """JLCPCB's standard stackup for this config, or None if none is on file (no silent gap)."""
    if not (copper_layers and thickness_mm):
        return None
    return STACKUPS.get((copper_layers, round(thickness_mm, 1)))


def parse_board_stackup(pcb_path: str | Path) -> list[dict]:
    """The board's dielectric+copper stackup layers top->bottom, or [] when none is defined."""
    try:
        data = sexpdata.loads(Path(pcb_path).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return []
    setup = _get(data, "setup")
    stk = _get(setup, "stackup") if setup else None
    if not stk:
        return []
    out: list[dict] = []
    for node in _getall(stk, "layer"):
        typ = str(_getval(node, "type") or "").lower()
        th = _getval(node, "thickness")
        if "copper" in typ:
            out.append({"type": "copper", "thickness": th})
        elif "prepreg" in typ or "core" in typ:
            out.append(
                {
                    "type": "core" if "core" in typ else "prepreg",
                    "thickness": th,
                    "epsilon_r": _getval(node, "epsilon_r"),
                }
            )
    return out


def _stackup_dielectric_mismatch(board_stk: list[dict], ref: dict) -> list[str]:
    """Human-readable dielectric (prepreg/core) thickness mismatches vs the JLCPCB reference."""
    ref_di = [layer for layer in ref["layers"] if layer["type"] in ("prepreg", "core")]
    brd_di = [layer for layer in board_stk if layer["type"] in ("prepreg", "core")]
    out: list[str] = []
    for i, rl in enumerate(ref_di):
        bl = brd_di[i] if i < len(brd_di) else None
        if bl is None or bl.get("thickness") is None:
            out.append(f"{rl['role']}: missing (JLCPCB {rl['thickness']} mm)")
        elif abs(float(bl["thickness"]) - rl["thickness"]) > 0.02:
            out.append(f"{rl['role']}: board {bl['thickness']} mm vs JLCPCB {rl['thickness']} mm")
    return out


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #
def board_rules(pro_path: str | Path | None) -> dict:
    """The configured ``design_settings.rules`` from a ``.kicad_pro`` (or {})."""
    if not pro_path:
        return {}
    try:
        d = json.loads(Path(pro_path).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    return (d.get("board") or {}).get("design_settings", {}).get("rules", {}) or {}


def board_thickness_mm(pcb_path: str | Path) -> float | None:
    """The finished board thickness from ``(general (thickness X))`` in the .kicad_pcb."""
    try:
        data = sexpdata.loads(Path(pcb_path).read_text(encoding="utf-8"))
        gen = _get(data, "general")
        t = _getval(gen, "thickness") if gen else None
        return float(t) if t is not None else None
    except (OSError, ValueError, TypeError):
        return None


def _f(severity: str, title: str, detail: str) -> dict:
    return {"severity": severity, "title": title, "detail": detail}


# --------------------------------------------------------------------------- #
# the check
# --------------------------------------------------------------------------- #
def check_jlcpcb_manufacturability(project) -> dict:
    """Grade a board against JLCPCB's published capabilities.

    Returns ``{manufacturable, layers, copper_oz, thickness_mm, limits, findings, sources,
    verified}``. ``manufacturable`` is False on any blocker (a real feature JLCPCB cannot make).
    Looser-than-JLCPCB *configured rules* are 'major' warnings (the fab is fine, but KiCad's DRC
    won't catch a sub-JLCPCB feature you add later).
    """
    if not project.pcb:
        from kicad_mcp.review.kicad import KiCadError

        raise KiCadError("No PCB to check against JLCPCB.")

    board = parse_board(project.pcb)
    limits = capabilities_for(board.copper_layers, board.copper_oz)
    findings: list[dict] = []

    # 1) actual geometry JLCPCB physically cannot make -> blockers
    widths = [t.width for t in board.tracks if t.width > 0]
    if widths and min(widths) < limits["min_track_width"] - 1e-6:
        findings.append(
            _f(
                "blocker",
                f"Thinnest track {min(widths):.3f} mm < JLCPCB min {limits['min_track_width']} mm",
                f"JLCPCB cannot reliably etch tracks below {limits['min_track_width']} mm on a "
                f"{board.copper_layers}-layer / {board.copper_oz:.0f} oz board. Widen them.",
            )
        )
    drills = [v.drill for v in board.vias if v.drill > 0]
    if drills and min(drills) < limits["min_via_drill"] - 1e-6:
        findings.append(
            _f(
                "blocker",
                f"Smallest via drill {min(drills):.3f} mm < JLCPCB min {limits['min_via_drill']} mm",
                "JLCPCB mechanical drilling cannot make a via hole this small. Enlarge the drill.",
            )
        )
    rings = [(v.size - v.drill) / 2 for v in board.vias if v.size > 0 and v.drill > 0]
    if rings and min(rings) < limits["min_annular_ring"] - 1e-6:
        findings.append(
            _f(
                "blocker",
                f"Smallest via annular ring {min(rings):.3f} mm < JLCPCB min "
                f"{limits['min_annular_ring']} mm",
                "Annular ring = (via diameter - drill) / 2. Increase the via pad or shrink the drill.",
            )
        )

    # 2) configured DRC rules looser than JLCPCB -> KiCad DRC won't catch sub-JLCPCB features
    rules = board_rules(project.pro)
    for key, limit_key, label in (
        ("min_copper_edge_clearance", "min_copper_edge_clearance", "copper-to-board-edge"),
        ("min_through_hole_diameter", "min_pth", "min plated hole"),
        ("min_track_width", "min_track_width", "min track width"),
        ("min_clearance", "min_clearance", "min clearance"),
        ("min_via_diameter", "min_via_diameter", "min via diameter"),
        ("min_via_annular_width", "min_annular_ring", "min annular ring"),
    ):
        cur = rules.get(key)
        jlc = limits[limit_key]
        if isinstance(cur, int | float) and cur < jlc - 1e-6:
            findings.append(
                _f(
                    "major",
                    f"DRC rule '{label}' = {cur} mm is looser than JLCPCB's {jlc} mm",
                    "KiCad's DRC will pass features JLCPCB can't make. Tighten this rule to the "
                    "JLCPCB minimum (or run `jlcpcb-apply-rules`).",
                )
            )

    # 3) stackup / layer-count / copper / thickness must be a JLCPCB-orderable combo
    if board.copper_oz and round(board.copper_oz, 1) not in SUPPORTED_COPPER_OZ:
        findings.append(
            _f(
                "major",
                f"Copper weight {board.copper_oz:.1f} oz is not a standard JLCPCB option",
                f"JLCPCB standard copper weights: {', '.join(f'{o:g}' for o in SUPPORTED_COPPER_OZ)} oz.",
            )
        )
    thickness = board_thickness_mm(project.pcb)
    if thickness and round(thickness, 2) not in SUPPORTED_THICKNESS_MM:
        findings.append(
            _f(
                "major",
                f"Board thickness {thickness} mm is not a standard JLCPCB option",
                f"JLCPCB standard thicknesses (mm): "
                f"{', '.join(f'{t:g}' for t in SUPPORTED_THICKNESS_MM)}.",
            )
        )

    # 4) stackup vs JLCPCB's published standard (informational; JLCPCB sets the final stack at order)
    ref = reference_stackup(board.copper_layers, thickness)
    board_stk = parse_board_stackup(project.pcb)
    if ref:
        if not board_stk:
            findings.append(
                _f(
                    "major",
                    f"No explicit stackup defined — JLCPCB's standard for "
                    f"{board.copper_layers}L/{thickness} mm is {ref['code']}",
                    "KiCad falls back to a generic stackup. If you rely on controlled impedance, set "
                    "the stack in KiCad Board Setup to JLCPCB's reference (in this report).",
                )
            )
        else:
            mismatch = _stackup_dielectric_mismatch(board_stk, ref)
            if mismatch:
                findings.append(
                    _f(
                        "major",
                        f"Stackup dielectrics differ from JLCPCB's standard {ref['code']}",
                        "Impedance/coupling won't match JLCPCB's build: " + "; ".join(mismatch),
                    )
                )
    elif (board.copper_layers or 0) >= 4:
        # 4+ layer boards have a JLCPCB impedance stackup; flag the gap rather than stay silent
        # (2-layer boards are a single core -- no impedance stackup -- so we say nothing there).
        findings.append(
            _f(
                "minor",
                f"No JLCPCB reference stackup on file for {board.copper_layers}L/{thickness} mm",
                f"Only common configs are vendored; the full set is at {STACKUP_SOURCE}.",
            )
        )

    manufacturable = not any(f["severity"] == "blocker" for f in findings)
    return {
        "manufacturable": manufacturable,
        "layers": board.copper_layers,
        "copper_oz": board.copper_oz,
        "thickness_mm": thickness,
        "limits": limits,
        "reference_stackup": ref,
        "findings": findings,
        "sources": [*SOURCES, STACKUP_SOURCE],
        "verified": VERIFIED,
    }
